### ISSUE TITLE
ButtonView.swift missing

### ISSUE THREAD

**Issue by LukeCrouch** [sheikhbayazid/User-Location-in-SwiftUI#1]
Thanks for uploading your Demo! Unfortunately I cannot build it because ButtonView.swift is missing:

error: Build input files cannot be found: '/Users/user/Documents/User-Location-Demo/User-Location-in-SwiftUI/LocationDemo/LocationDemo/Location/LocationPass.swift', '/Users/user/Documents/User-Location-Demo/User-Location-in-SwiftUI/LocationDemo/LocationDemo/ButtonView.swift' (in target 'LocationDemo' from project 'LocationDemo')

**Comment by sheikhbayazid** [comment]
Sorry for the late response...
Here's the complete code of the Button View (You need to create a new ButtonView and just paste the code)




import SwiftUI

struct ButtonView: View {
    var body: some View {
        
        ZStack{
            Color(red: 224/255, green: 229/255, blue: 236/255)
            VStack{
                VStack {
                    Image(systemName: "b.square.fill")
                        .resizable()
                        .foregroundColor(.blue)
                        .frame(width: 70, height: 70)
                        .padding()
                        //.background(Color(red: 244/255, green: 229/255, blue: 236/255))
                        .cornerRadius(20)
                        .shadow(color: Color.white, radius: 8, x: -8, y: -8)
                        .shadow(color: Color(red: 163/255, green: 177/255, blue: 198/255), radius: 8, x: 9, y: 9)
                    
                }.shadow(color: Color.white, radius: 8, x: -8, y: -8)
                    .shadow(color: Color(red: 163/255, green: 177/255, blue: 198/255), radius: 8, x: 9, y: 9)
                
                VStack {
                    Image(systemName: "a.square.fill")
                        .resizable()
                        .foregroundColor(.blue)
                        .frame(width: 70, height: 70)
                        .padding()
                        //.background(Color(red: 244/255, green: 229/255, blue: 236/255))
                        .cornerRadius(20)
                        .shadow(color: Color.white, radius: 8, x: -8, y: -8)
                        .shadow(color: Color(red: 163/255, green: 177/255, blue: 198/255), radius: 8, x: 9, y: 9)
                    
                }.shadow(color: Color.white, radius: 8, x: -8, y: -8)
                    .shadow(color: Color(red: 163/255, green: 177/255, blue: 198/255), radius: 8, x: 9, y: 9)
                
                VStack {
                    Image(systemName: "y.square.fill")
                        .resizable()
                        .foregroundColor(.blue)
                        .frame(width: 70, height: 70)
                        .padding()
                        //.background(Color(red: 244/255, green: 229/255, blue: 236/255))
                        .cornerRadius(20)
                        .shadow(color: Color.white, radius: 8, x: -8, y: -8)
                        .shadow(color: Color(red: 163/255, green: 177/255, blue: 198/255), radius: 8, x: 9, y: 9)
                    
                }.shadow(color: Color.white, radius: 8, x: -8, y: -8)
                    .shadow(color: Color(red: 163/255, green: 177/255, blue: 198/255), radius: 8, x: 9, y: 9)
                
                VStack {
                    Image(systemName: "a.square.fill")
                        .resizable()
                        .foregroundColor(.blue)
                        .frame(width: 70, height: 70)
                        .padding()
                        //.background(Color(red: 244/255, green: 229/255, blue: 236/255))
                        .cornerRadius(20)
                        .shadow(color: Color.white, radius: 8, x: -8, y: -8)
                        .shadow(color: Color(red: 163/255, green: 177/255, blue: 198/255), radius: 8, x: 9, y: 9)
                    
                }.shadow(color: Color.white, radius: 8, x: -8, y: -8)
                    .shadow(color: Color(red: 163/255, green: 177/255, blue: 198/255), radius: 8, x: 9, y: 9)
                
                VStack {
                    Image(systemName: "z.square.fill")
                        .resizable()
                        .foregroundColor(.blue)
                        .frame(width: 70, height: 70)
                        .padding()
                        //.background(Color(red: 244/255, green: 229/255, blue: 236/255))
                        .cornerRadius(20)
                        .shadow(color: Color.white, radius: 8, x: -8, y: -8)
                        .shadow(color: Color(red: 163/255, green: 177/255, blue: 198/255), radius: 8, x: 9, y: 9)
                    
                }.shadow(color: Color.white, radius: 8, x: -8, y: -8)
                    .shadow(color: Color(red: 163/255, green: 177/255, blue: 198/255), radius: 8, x: 9, y: 9)
                
                VStack {
                    Image(systemName: "i.square.fill")
                        .resizable()
                        .foregroundColor(.blue)
                        .frame(width: 70, height: 70)
                        .padding()
                        //.background(Color(red: 244/255, green: 229/255, blue: 236/255))
                        .cornerRadius(20)
                        .shadow(color: Color.white, radius: 8, x: -8, y: -8)
                        .shadow(color: Color(red: 163/255, green: 177/255, blue: 198/255), radius: 8, x: 9, y: 9)
                    
                }.shadow(color: Color.white, radius: 8, x: -8, y: -8)
                    .shadow(color: Color(red: 163/255, green: 177/255, blue: 198/255), radius: 8, x: 9, y: 9)
                
                VStack {
                    Image(systemName: "d.circle.fill")
                        .resizable()
                        .foregroundColor(.blue)
                        .frame(width: 70, height: 70)
                        .padding()
                        //.background(Color(red: 244/255, green: 229/255, blue: 236/255))
                        .cornerRadius(20)
                        .shadow(color: Color.white, radius: 8, x: -8, y: -8)
                        .shadow(color: Color(red: 163/255, green: 177/255, blue: 198/255), radius: 8, x: 9, y: 9)
                    
                }.shadow(color: Color.white, radius: 8, x: -8, y: -8)
                    .shadow(color: Color(red: 163/255, green: 177/255, blue: 198/255), radius: 8, x: 9, y: 9)
            }
        }.edgesIgnoringSafeArea(.all)
        
        
    }
}

struct ButtonView_Previews: PreviewProvider {
    static var previews: some View {
        ButtonView()
    }
}

**Comment by sheikhbayazid** [comment]
Hey Sorry for the late response...
Delete the codes where you find ButtonView. All should work just fine you do it.
